//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Toc
{

    private TocItem[] tocItemField;

    private string supportedProductField;

    private string supportedVersionField;

    private string rootPathField;

    private string urlPrefixField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TocItem")]
    public TocItem[] TocItem
    {
        get
        {
            return this.tocItemField;
        }
        set
        {
            this.tocItemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SupportedProduct
    {
        get
        {
            return this.supportedProductField;
        }
        set
        {
            this.supportedProductField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SupportedVersion
    {
        get
        {
            return this.supportedVersionField;
        }
        set
        {
            this.supportedVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RootPath
    {
        get
        {
            return this.rootPathField;
        }
        set
        {
            this.rootPathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UrlPrefix
    {
        get
        {
            return this.urlPrefixField;
        }
        set
        {
            this.urlPrefixField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class TocItem
{

    private TocItem[] tocItem1Field;

    private string textField;

    private string urlField;

    private string sEODescriptionField;

    private string scopeField;

    private string versionField;

    private string childrenField;


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TocItem")]
    public TocItem[] TocItem1
    {
        get
        {
            return this.tocItem1Field;
        }
        set
        {
            this.tocItem1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SEODescription
    {
        get
        {
            return this.sEODescriptionField;
        }
        set
        {
            this.sEODescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Scope
    {
        get
        {
            return this.scopeField;
        }
        set
        {
            this.scopeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Children
    {
        get
        {
            return this.childrenField;
        }
        set
        {
            this.childrenField = value;
        }
    }
}
