//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Graph.WebRole.Resources.GraphExplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Graph.WebRole.Resources.GraphExplorer.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string METHOD {
            get {
                return ResourceManager.GetString("METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request body.
        /// </summary>
        public static string REQUEST_BODY {
            get {
                return ResourceManager.GetString("REQUEST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request header.
        /// </summary>
        public static string REQUEST_HEADER {
            get {
                return ResourceManager.GetString("REQUEST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response.
        /// </summary>
        public static string RESPONSE {
            get {
                return ResourceManager.GetString("RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string SIGN_IN {
            get {
                return ResourceManager.GetString("SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string SIGNOUT {
            get {
                return ResourceManager.GetString("SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code.
        /// </summary>
        public static string STATUS_CODE {
            get {
                return ResourceManager.GetString("STATUS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To try the explorer, please.
        /// </summary>
        public static string TRY_IN_EXPLORER {
            get {
                return ResourceManager.GetString("TRY_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using demo tenant.
        /// </summary>
        public static string USING_DEMO_TENANT {
            get {
                return ResourceManager.GetString("USING_DEMO_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with your work or school account from Microsoft..
        /// </summary>
        public static string WORK_WITH_SCHOOL_OFFICE {
            get {
                return ResourceManager.GetString("WORK_WITH_SCHOOL_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
